version: '2.1'

networks:
  conpot_local:

services:

# Conpot service
  conpot:
    container_name: conpot
    restart: always
    networks:
     - conpot_local
    ports:
     - "1025:1025"
     - "50100:50100"
    image: "dtagdevsec/conpot:1710"
    volumes:
     - /data/conpot/log:/var/log/conpot
