version: '2.1'

networks:
  cowrie_local:

services:

# Cowrie service
  cowrie:
    container_name: cowrie
    restart: always
    networks:
     - cowrie_local
    cap_add:
     - NET_BIND_SERVICE
    ports:
     - "22:2222"
     - "23:2223"
    image: "loanbo/cowrie:latest"
    volumes:
     - /data/cowrie/downloads:/cowrie/cowrie-gi/dl
     - /data/cowrie/keys:/cowrie/cowrie-gi/etc
     - /data/cowrie/log:/cowrie/cowrie-gi/log
     - /data/cowrie/log/tty:/cowrie/cowrie-gi/log/tty
